### ISSUE TITLE
Caliper 1.1.34 Crash

### ISSUE THREAD

**Issue by mitchej123** [JarHax/Caliper#9]
```
[21:22:31] [main/ERROR] [Caliper]: Unable to parse event listener: ASM: Butterflies & Moths onSyncBreedingTracker(Lforestry/api/core/ForestryEvent$SyncedBreedingTracker;)V.
[21:22:31] [main/ERROR] [Caliper]: Catching
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1967) ~[?:1.8.0_171]
    at net.darkhax.caliper.profiling.profilers.events.EventInfo.<init>(EventInfo.java:34) ~[EventInfo.class:?]
    at net.darkhax.caliper.profiling.profilers.events.ProfileEvents.scrapeEventBusses(ProfileEvents.java:85) ~[ProfileEvents.class:?]
    at net.darkhax.caliper.profiling.profilers.events.ProfileEvents.onLoadComplete(ProfileEvents.java:34) ~[ProfileEvents.class:?]
    at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_171]
    at net.darkhax.caliper.Caliper.onLoadComplete(Caliper.java:80) [Caliper.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627) [FMLModContainer.class:?]
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
[Snip]
```

Specific Line:
```java
this.method = eventInfo.substring(0, eventInfo.indexOf('('));
```

Based on reports from other people, it seems to be some  interactions with Caliper & Vampirism (1.4.3), and the crash stops with either disabled.

**Comment by Darkhax** [comment]
Your PR should adequately fix this issue? If not let me know and give some more info and I can clean this code up some more.
